version: "2"
services:
  app:
    build:
      context: .
      dockerfile: ./config/Dockerfile-app
    volumes:
      - ./:/app
    links:
      - datastore
    environment:
      DATASTORE_EMULATOR_HOST: datastore:8432
      GCLOUD_PROJECT: test
  datastore:
    build:
      context: .
      dockerfile: ./config/Dockerfile-sdk
    expose:
      - 8432
